---
# =================================================================================================
# Area labels - Pull Requests
# =================================================================================================
- name: area/devcontainer
  color: "0000FF"
  description: Changes made to the DevContainer configuration

- name: area/github
  color: "000000" # GitHub Black
  description: Changes made in the github directory

- name: area/docker
  color: "0db7ed" # Docker Cerulean
  description: Changes made in the infrastructure directory

# =================================================================================================
# Renovate Types
# =================================================================================================
- name: renovate/container
  color: "3970E4"
- name: renovate/github-action
  color: "000000"

# =================================================================================================
# Semantic Types
# =================================================================================================
- name: type/digest
  color: "ffeC19"
- name: type/patch
  color: "ffeC19"
- name: type/minor
  color: "ff9800"
- name: type/major
  color: "f6412d"

# =================================================================================================
# Size Labels
# =================================================================================================
- name: size/XS
  color: "0000ff"
- name: size/S
  color: "000ff0"
- name: size/M
  color: "00ff00"
- name: size/L
  color: "0ff000"
- name: size/XL
  color: "ff0000"
- name: size/XXL
  color: "ff00ff"

# =================================================================================================
# Issue Types
# =================================================================================================
- name: issue/bug
  color: "ff0000"
- name: issue/feature
  color: "00ff00"
- name: issue/chore
  color: "0000ff"
