[tools]
# Runtimes
node = "22.13.0"
python = "3.13.1"

# Terraform Stuff: https://mise.jdx.dev/mise-cookbook/terraform.html
terraform = "1.10.4"
"aqua:terraform-linters/tflint" = "0.55.0"

# Secret Encryption Stuff
"aqua:getsops/sops" = "3.9.3"
"aqua:FiloSottile/age" = "1.2.1"

# Flux Stuff
"aqua:fluxcd/flux2" = "2.4.0"
# "aqua:flux-iac/tofu-controller/tfctl" = "0.15.0"

# Kubectl + Plugins
"aqua:kubernetes/kubectl" = "1.32.1"
# kubecolor
# kubectl-switch
# kubectl-pgo

# Misc K8S Tools
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:helm/helm" = "3.13.0"
"aqua:derailed/k9s" = "0.32.7"
"aqua:stern/stern" = "1.31.0"

# Talos Stuff
"aqua:siderolabs/talos" = "1.9.0"
"aqua:budimanjojo/talhelper" = "3.0.15"
# talswitcher

# Misc Tools
"aqua:go-task/task" = "3.38.0"
# minio cli
"mom:@bitwarden/cli" = "v2024.8.1"
"aqua:cert-manager/cmctl" = "2.1.1"
"aqua:jqlang/jq" = "1.7.1"
"aqua:mikefarah/yq" = "3.4.3"

# Linters
"pipx:yamllint" = "1.35.1"
