---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Docker Release

on:
  workflow_dispatch:
    inputs:
      custom-tag:
        type: string
        description: Additional custom tags for the image.
        required: false
  pull_request:
    branches: ["main"]
    paths:
      - Dockerfile
  push:
    tags: ["*"]

jobs:
  release:
    uses: mirceanton/reusable-workflows/.github/workflows/docker-release.yaml@main
    secrets: inherit
    with:
      image-name: ghcr.io/${{ github.repository }}
      platforms: linux/amd64
      custom-tag: ${{ inputs.custom-tag }}
