---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Docker Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        default: true
        required: false
        type: boolean
      custom-tag:
        type: string
        description: Additional custom tags for the image.
        required: false

  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/docker-release.yaml
      - Dockerfile
      - requirements.txt

  push:
    tags: ["*"]

jobs:
  release:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-docker-build-push.yaml@240678cf33f0c0c65f0323615c925f0312b2d640 # v3.4.27
    secrets: inherit
    with:
      image: ghcr.io/${{ github.repository }}
      platforms: linux/amd64
      tags: |
        type=ref,event=tag
        type=ref,event=pr
        ${{ inputs.custom-tag }}
      context: .
      dockerfile: ./Dockerfile
      dry-run: "${{ inputs.dry-run == true }}"
