---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Git Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry run
        default: true
        required: false
        type: boolean

  pull_request:
    paths:
      - ".github/workflows/git-release.yaml"
      - "README.md"

  push:
    branches: ["main"]
    paths:
      - "README.md"

jobs:
  release:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-release-calver.yaml@0d9c406821566c38302d9af7c59ccfc4d6416c68 # v3.4.46
    secrets: inherit
    with:
      dry-run: ${{ inputs.dry-run || github.event_name == 'pull_request' }}
