---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@c2dc5ba45f0a8b29e0c5d46f70295efff63984ab # v3.7.1
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
