---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@c60bb9813e634b15663d4ff01027e3b32102aef4 # v3.7.2
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
