---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  # Manual Trigger
  workflow_dispatch: {}

  # Run on any PR
  pull_request: {}

jobs:
  actionlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-actionlint.yaml@8c6cf153c5b381b14b33f0f8ac9bd97d8e2d5c0d # v3.4.37
    secrets: inherit

  commitlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-commitlint.yaml@8c6cf153c5b381b14b33f0f8ac9bd97d8e2d5c0d # v3.4.37
    secrets: inherit
