---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  # Manual Trigger
  workflow_dispatch: {}

  # Run on any PR
  pull_request: {}

jobs:
  actionlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-actionlint.yaml@96e57c64eb8f41dca9eb0ca6f8e57e8512811927 # v3.4.35
    secrets: inherit

  commitlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-commitlint.yaml@96e57c64eb8f41dca9eb0ca6f8e57e8512811927 # v3.4.35
    secrets: inherit
