---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  # Manual Trigger
  workflow_dispatch: {}

  # Run on any PR
  pull_request: {}

jobs:
  actionlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-actionlint.yaml@e923b666f157f12715483c3fd0e0d466d9af9325 # v3.4.39
    secrets: inherit

  commitlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-commitlint.yaml@e923b666f157f12715483c3fd0e0d466d9af9325 # v3.4.39
    secrets: inherit
