---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  # Manual Trigger
  workflow_dispatch: {}

  # Run on any PR
  pull_request: {}

jobs:
  actionlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-actionlint.yaml@fff460c54de9bc557d89108af5b6e093629f9605 # v3.4.48
    secrets: inherit

  commitlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-commitlint.yaml@fff460c54de9bc557d89108af5b6e093629f9605 # v3.4.48
    secrets: inherit
