---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  # Manual Trigger
  workflow_dispatch: {}

  # Run on any PR
  pull_request: {}

jobs:
  actionlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-actionlint.yaml@e7fc0b68ce5b8bf0f4c85d53928f91af6ec54357 # v3.4.36
    secrets: inherit

  commitlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-commitlint.yaml@e7fc0b68ce5b8bf0f4c85d53928f91af6ec54357 # v3.4.36
    secrets: inherit
