---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Meta - Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/meta-labeler.yaml@8343dab107e640303a30a4d4a7af2d5eb257e817
    secrets: inherit
    with:
      config-file: ".github/configs/labeler.yaml"
