---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Meta: PR Labeler"

on:
  workflow_dispatch: {} # Manual Trigger
  pull_request_target: {}

jobs:
  labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/meta-labeler.yaml@main
    secrets: inherit
    with:
      config-file: .github/configs/labeler.yaml
