---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: README Generator

on:
  workflow_dispatch: {}

  push:
    branches: ["main"]

  pull_request:
    paths:
      - ".github/workflows/readme-generator.yaml"
      - ".github/scripts/README_template.j2"
      - ".github/scripts/readme-generator.py"
      - "Dockerfile"
      - "requirements.txt"

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2.0.2
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install Jinja2

      - name: Generate README
        working-directory: .github/scripts
        run: python3 readme-generator.py

      - name: Show changes
        run: cat README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5
        if: "${{ github.event_name == 'push' }}"
        with:
          commit_message: "[bot] Update README"
          file_pattern: "README.md"
          branch: ${{ github.ref }}
